name: Terraform Plan

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          AWS_REGION: us-east-1
          TF_VAR_project_name: fastapi-floci-demo
          TF_VAR_environment: dev
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD_DEV }}
